name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm install
          npm install electron-builder-squirrel-windows
          npm run postinstall

      - name: Build project
        run: |
          npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win
